src/OpenInPdfChatBot/website/__init__.py
from flask import Flask
from .views import views


def create_app():
    app = Flask(__name__)
    app.config["SECRET_KEY"] = "my_key"
    app.register_blueprint(views, url_prefix="/")
    return app

src/OpenInPdfChatBot/website/views.py
from flask import Blueprint, render_template, request, flash, send_from_directory
from src.OpenInPdfChatBot.components.user_input_reader import user_input_handler
from src.OpenInPdfChatBot.constants import PDF_FILE_DIR
import os
from src.OpenInPdfChatBot import logger

views = Blueprint('views', __name__)


@views.route('/', methods=["GET", "POST"])
@views.route('/home', methods=["GET", "POST"])
def home():
    result = ""
    if request.method == "POST":
        question = request.form.get('question')
        if not question:
            flash("Field is empty", category='error')
        else:
            flash("Question submitted", category='success')
            result = user_input_handler(question)

    return render_template('home.html', result=result)


@views.route('/<filename>')
def serve_pdf(filename):

    logger.info(f"Requested file: {filename}")
    directory = os.path.abspath(PDF_FILE_DIR)
    return send_from_directory(directory, filename)

src/OpenInPdfChatBot/website/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet"
              type="text/css"
              href="{{ url_for('static',filename='styles/home.css') }}">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
              rel="stylesheet"
              integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
              crossorigin="anonymous">
        <script src="https://kit.fontawesome.com/b57d3e3e05.js"
                crossorigin="anonymous"></script>
        <title>
            {% block title %}
            {% endblock title %}
        </title>
    </head>
    <body>
        <nav class="navbar navbar-expand-lg bg-body-tertiary" data-bs-theme="dark">
            <div class="container-fluid">
                <button class="navbar-toggler"
                        type="button"
                        data-bs-toggle="collapse"
                        data-bs-target="#navbarNav"
                        aria-controls="navbarNav"
                        aria-expanded="false"
                        aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="/home">Home</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        <div>
            {% with messages=get_flashed_messages(with_categories=True) %}
                {% for category,message in messages %}
                    {% if category=="error" %}
                        <div class="alert alert-danger alert-dismissible fade show" role="alert">
                            {{ message }}
                            <button type="button"
                                    class="btn-close"
                                    data-bs-dismiss="alert"
                                    aria-label="Close"></button>
                        </div>
                    {% else %}
                        <div class="alert alert-success alert-dismissible fade show" role="alert">
                            {{ message }}
                            <button type="button"
                                    class="btn-close"
                                    data-bs-dismiss="alert"
                                    aria-label="Close"></button>
                        </div>
                    {% endif %}
                {% endfor %}
            {% endwith %}
        </div>
        <div class="container">
            {% block content %}
            {% endblock content %}
        </div>
    </body>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
    <script type="text/javascript"
            src="{{url_for('static',filename='scripts/index.js')}}"></script>
    <!-- Footer -->
    <!-- footer section-->
    <footer id="footer" class="justify-content-between align-items-center">
        <div class="container-fluid">
            <!-- social media icons -->
            <div class="social-icons mt-4">
                <a href="mailto:rashambinf@gmail.com" target="_blank"><i class="far fa-envelope"></i></a>
                <a href="https://www.instagram.com/muhlis_c_mohd/" target="_blank"><i class="fab fa-instagram"></i></a>
                <a href="https://www.linkedin.com/in/muhliscm/" target="_blank"><i class="fab fa-linkedin"></i></a>
                <a href="https://github.com/Muhliscm" target="_blank"><i class="fab fa-github"></i></a>
            </div>
        </div>
        <p class="copyright">&copy; MUHLIS CM</p>
    </footer>
    <!-- Bootstrap JS -->
</html>

src/OpenInPdfChatBot/website/templates/home.html
{% extends "base.html" %}
{% block title %}
    chat bot
{% endblock title %}
{% block content %}
    <div>
        <!-- Second heading and image -->
        <h1 align='center'>Ask Your Question to bot</h1>
        <form method='POST'>
            <textarea class="form-control" rows="5" id="question" name="question"></textarea>
            <br>
            <div align='center'>
                <div>
                    <button type="submit"  id="chat" class="btn btn-primary">Submit</button>
                </div>
            </div>
            <br>
            <div align="center">
                <a href="/home">
                    <button type="submit" class="btn btn-secondary">Ask Again</button>
                </a>
            </div>
        </form>
        <div id="answer">
            {% if result %}
                <div>
                    <h1>Question: {{ result.Question }}</h1>
                    <br>
                    <h3>
                        Answer :{{ result.Answer }}
                    </h2>
                </div>
                <br>
                {% if result.References %}
                    <div>
                        <h3>References:</h3>
                        <br>
                        {% for ref in result.References %}
                            <div class="card-body">
                                <h5 class="card-title">
                                    <a href="{{ url_for('views.serve_pdf', filename=ref['Document Name']) }}"
                                       target="_blank">{{ ref["Document Name"] }}</a>
                                </h5>
                                <br>
                                <p class="card-text">{{ ref.Paragraph }}</p>
                            </div>
                            <br>
                        {% endfor %}
                    </div>
                {% endif %}
            {% endif %}
        </div>
    {% endblock content %}